InventoryManagement/Models/StockItem.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventoryManagement.Models
{
    [Table("StockItem")]
    public class StockItem
    {
        [Key]
        public int ProductId { get; set; }
        
        [StringLength(60, MinimumLength = 3)]
        [Required]
        public required string Description { get; set; }

        [Display(Name = "Stock Amount")]
        public int StockAmount { get; set; }

        [Display(Name = "Safe Stock Amount")]
        public int SafeStockAmount { get; set; }

        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Price { get; set; }
    }
}

InventoryManagement/Controllers/StockItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InventoryManagement.Data;
using InventoryManagement.Models;

namespace InventoryManagement.Controllers
{
    public class StockItemsController : Controller
    {
        private readonly InventoryManagementContext _db;

        public StockItemsController(InventoryManagementContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index(string searchString)
        {
            if (_db.StockItems == null)
            {
                return Problem("Entity set 'InventoryManagementContext.StockItems'  is null.");
            }

            var stockItems = from m in _db.StockItems
                             select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                stockItems = stockItems.Where(s => s.Description!.Contains(searchString) || s.ProductId.ToString() == searchString);
            }

            return View(await stockItems.ToListAsync());
        }

        // GET: StockItems/Details/ProductId
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stockItem = await _db.StockItems
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (stockItem == null)
            {
                return NotFound();
            }

            return View(stockItem);
        }

        // GET: StockItems/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StockItems/Create/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,Description,StockAmount,SafeStockAmount,Price")] StockItem stockItem)
        {
            if (ModelState.IsValid)
            {
                _db.Add(stockItem);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(stockItem);
        }

        // GET: StockItems/Edit/ProductId
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stockItem = await _db.StockItems.FindAsync(id);
            if (stockItem == null)
            {
                return NotFound();
            }
            return View(stockItem);
        }

        // POST: StockItems/Edit/ProductId/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,Description,StockAmount,SafeStockAmount,Price")] StockItem stockItem)
        {
            if (id != stockItem.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(stockItem);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StockItemExists(stockItem.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            return View(stockItem);
        }

        // GET: StockItems/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stockItem = await _db.StockItems
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (stockItem == null)
            {
                return NotFound();
            }

            return View(stockItem);
        }

        // POST: StockItems/Delete/{id}
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var stockItem = await _db.StockItems.FindAsync(id);
            if (stockItem != null)
            {
                _db.StockItems.Remove(stockItem);
            }

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StockItemExists(int id)
        {
            return _db.StockItems.Any(e => e.ProductId == id);
        }
    }
}

InventoryManagement/Views/StockItems/Create.cshtml
@model InventoryManagement.Models.StockItem

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>StockItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockAmount" class="control-label"></label>
                <input asp-for="StockAmount" class="form-control" />
                <span asp-validation-for="StockAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SafeStockAmount" class="control-label"></label>
                <input asp-for="SafeStockAmount" class="form-control" />
                <span asp-validation-for="SafeStockAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InventoryManagement/Views/StockItems/Delete.cshtml
@model InventoryManagement.Models.StockItem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StockItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SafeStockAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SafeStockAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InventoryManagement/Views/StockItems/Details.cshtml
@model InventoryManagement.Models.StockItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>StockItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SafeStockAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SafeStockAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ProductId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InventoryManagement/Views/StockItems/Edit.cshtml
@model InventoryManagement.Models.StockItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>@Model.Description</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-route-id="@Model?.ProductId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId" />
            <input type="hidden" asp-for="Description" />
            <div class="form-group">
                <label asp-for="StockAmount" class="control-label"></label>
                <input asp-for="StockAmount" class="form-control" />
                <span asp-validation-for="StockAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SafeStockAmount" class="control-label"></label>
                <input asp-for="SafeStockAmount" class="form-control" />
                <span asp-validation-for="SafeStockAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InventoryManagement/Views/StockItems/Index.cshtml
@model IEnumerable<InventoryManagement.Models.StockItem>

@{
    ViewData["Title"] = "Index";
}

<h1>Inventory Management</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="StockItems" asp-action="Index">
    <p>
        Title: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StockAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SafeStockAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StockAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SafeStockAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ProductId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ProductId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ProductId">Delete</a> |
                <a asp-action="Sell" asp-route-id="@item.ProductId">Sell</a>
            </td>
        </tr>
}
    </tbody>
</table>